const { withTransaction } = require('../shared/withTransaction');
const accountingService = require('../accounting/accounting.service');
const accountingRepository = require('../accounting/accounting.repository');
const accountingRules = require('../accounting/accounting.rules');
const accountsRepository = require('../accounts/accounts.repository');
const organizationsRepository = require('../organizations/organizations.repository');

/**
 * Journal Entries Service
 *
 * The thin layer between HTTP and the ledger engine. It opens the transaction
 * and hands the client to accounting.service, which does the posting.
 *
 * NOTHING HERE IMPLEMENTS DOUBLE-ENTRY. If a future change makes it tempting
 * to build lines or check a balance in this file, that belongs in
 * accounting/ instead — one engine, called from everywhere.
 */

/** The system account that absorbs the opening-balance difference. */
const OPENING_EQUITY_CODE = '3010';

/** @private */
function fail(message, statusCode) {
  const error = new Error(message);
  error.statusCode = statusCode;
  throw error;
}

/** @private */
async function fiscalStartMonthFor(organizationId) {
  const organization = await organizationsRepository.findById(null, organizationId);
  // Phase 0 Decision A3: April, the Indian financial year.
  return organization?.fiscal_year_start_month || 4;
}

const journalEntriesService = {
  /**
   * @param {string} organizationId
   * @param {object} query
   * @returns {Promise<{ items: Array, pagination: object }>}
   */
  async listEntries(organizationId, query) {
    return accountingRepository.listEntries(null, organizationId, query);
  },

  /**
   * @param {string} organizationId
   * @param {string} entryId
   * @returns {Promise<object>}
   */
  async getEntry(organizationId, entryId) {
    const entry = await accountingRepository.findEntryWithLines(null, organizationId, entryId);
    // An entry in another organization is reported as missing, never as
    // forbidden — a 403 would confirm it exists.
    if (!entry) fail('Journal entry not found', 404);
    return entry;
  },

  /**
   * Post a manual journal entry. It posts immediately; there is no draft step
   * at this API surface, because a draft that can never be edited into balance
   * is not useful and one that can would need the whole edit path this phase
   * deliberately does not build.
   *
   * @param {object} params
   * @returns {Promise<object>}
   */
  async createEntry({ organizationId, actorUserId, data, ipAddress = null }) {
    const fiscalStartMonth = await fiscalStartMonthFor(organizationId);

    return withTransaction(async (client) =>
      accountingService.postJournalEntry(client, {
        organizationId,
        journalId: data.journal_id,
        entryDate: data.entry_date,
        lines: data.lines,
        reference: data.reference,
        narration: data.narration,
        // project.md §4.5's flag: false, because a person typed this one.
        isAutoGenerated: false,
        sourceType: 'manual',
        sourceId: null,
        actorUserId,
        ipAddress,
        fiscalStartMonth,
      })
    );
  },

  /**
   * Reverse a posted entry.
   *
   * @param {object} params
   * @returns {Promise<{ original: object, reversal: object }>}
   */
  async reverseEntry({ organizationId, actorUserId, entryId, reason, reversalDate, ipAddress = null }) {
    return withTransaction(async (client) =>
      accountingService.reverseJournalEntry(client, entryId, reason, {
        organizationId,
        actorUserId,
        ipAddress,
        reversalDate,
      })
    );
  },

  /**
   * Post the organization's opening balances as ONE balancing entry against
   * Opening Balance Equity.
   *
   * project.md §4.3 wants opening balances to seed the Balance Sheet. Doing it
   * as a real journal entry rather than a column every report special-cases is
   * what keeps the Balance Sheet a single query over the ledger — and it means
   * the opening position is auditable and reversible like anything else.
   *
   * Idempotent: a second call is refused rather than double-counting.
   *
   * @param {object} params
   * @returns {Promise<object|null>} The entry, or null when every balance is zero.
   */
  async postOpeningBalances({ organizationId, actorUserId, journalId, entryDate, ipAddress = null }) {
    const existing = await accountingRepository.listEntries(null, organizationId, {
      limit: 1,
      // source_type is set to 'opening_balance' below, so finding one means
      // this has already been done.
      search: '',
    });

    const alreadyPosted = existing.items.some((entry) => entry.source_type === 'opening_balance');
    if (alreadyPosted) {
      fail('Opening balances have already been posted for this organization', 409);
    }

    const accounts = await accountsRepository.listAll(null, organizationId, { status: 'active' });

    const equityAccount = accounts.find((account) => account.code === OPENING_EQUITY_CODE);
    if (!equityAccount) {
      fail('The Opening Balance Equity account is missing from this chart of accounts', 409);
    }

    const lines = accountingRules.openingBalances({
      accounts,
      openingEquityAccountId: equityAccount.id,
      description: 'Opening balance',
    });

    // Every opening balance is zero, so there is genuinely nothing to post.
    if (!lines) return null;

    const fiscalStartMonth = await fiscalStartMonthFor(organizationId);

    return withTransaction(async (client) =>
      accountingService.postJournalEntry(client, {
        organizationId,
        journalId,
        entryDate,
        lines,
        reference: 'Opening balances',
        narration: 'Opening balances posted against Opening Balance Equity',
        isAutoGenerated: true,
        sourceType: 'opening_balance',
        sourceId: null,
        actorUserId,
        ipAddress,
        fiscalStartMonth,
      })
    );
  },
};

module.exports = journalEntriesService;
